# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('feature', models.BooleanField()),
                ('activeyn', models.BooleanField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
