# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20170329_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('release_date', models.DateTimeField()),
                ('publish_date', models.DateTimeField()),
                ('cover_url', models.TextField()),
                ('feature', models.BooleanField()),
                ('activeyn', models.BooleanField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ManyToManyField(to='application.artist')),
                ('category', models.ManyToManyField(to='application.category')),
            ],
        ),
    ]
