# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='publish_date',
        ),
    ]
