# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20170401_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='cover_url',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
