# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_artist_cover_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='cover_url',
            new_name='cover_image',
        ),
    ]
