# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 10:26
from __future__ import unicode_literals

from django.db import migrations, models
#import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20170404_1756'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='album',
        #     name='cover_image',
        #     field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='/bsongs/mpd_test'),
        # ),
    ]
