# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20170413_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.TextField(),
        ),
    ]
