# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20170413_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('cover_image', models.TextField()),
                ('mp3_url', models.TextField()),
                ('m_order', models.IntegerField(default=0)),
                ('activeyn', models.BooleanField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('cover_image', models.TextField()),
                ('mpd_url', models.TextField()),
                ('mp4_url', models.TextField()),
                ('type', models.IntegerField(default=0)),
                ('activeyn', models.BooleanField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='video',
            field=models.ManyToManyField(to='application.video'),
        ),
        migrations.AddField(
            model_name='album',
            name='tracks',
            field=models.ManyToManyField(to='application.track'),
        ),
        migrations.AddField(
            model_name='album',
            name='trailer',
            field=models.ManyToManyField(to='application.video'),
        ),
    ]
