# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20170414_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='type',
            new_name='m_order',
        ),
        migrations.AddField(
            model_name='track',
            name='category',
            field=models.ManyToManyField(to='application.category'),
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.ManyToManyField(to='application.category'),
        ),
    ]
