# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_category_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='trailer',
            new_name='video',
        ),
    ]
